language: node_js
node_js:
  - "node"
after_success:
  - npm run coveralls
deploy:
  - provider: s3
    access_key_id: "YOUR AWS ACCESS KEY"
    secret_access_key: "YOUR AWS SECRET KEY"
    bucket: "amos-deploy-dev"
    region: eu-west-1
    local-dir: deployment-build
    on:
      branch: feature-32-travis-deployment
  - provider: codedeploy
    access_key_id: "YOUR AWS ACCESS KEY"
    secret_access_key: "YOUR AWS SECRET KEY"
    bucket: "amos-deploy-dev"
    key: deployment-build/latest.zip
    application: amos-app
    deployment_group: amos-master
    region: eu-west-1
    on:
      branch: feature-32-travis-deployment 
